# Generated by Django 3.0.3 on 2020-04-14 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200325_0554'),
    ]

    operations = [
        migrations.CreateModel(
            name='AirBnb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True)),
                ('host_id', models.TextField(blank=True, null=True)),
                ('host_name', models.TextField(blank=True, null=True)),
                ('neighbourhood_group', models.TextField(blank=True, null=True)),
                ('latitude', models.TextField(blank=True, null=True)),
                ('longitude', models.TextField(blank=True, null=True)),
                ('price', models.TextField(blank=True, null=True)),
                ('minimum_nights', models.TextField(blank=True, null=True)),
                ('number_of_reviews', models.TextField(blank=True, null=True)),
                ('last_review', models.TextField(blank=True, null=True)),
                ('reviews_per_month', models.TextField(blank=True, null=True)),
                ('calculated_host_listings_count', models.TextField(blank=True, null=True)),
                ('availability_365', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
