# Generated by Django 3.0.3 on 2020-04-14 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_airbnb'),
    ]

    operations = [
        migrations.AddField(
            model_name='airbnb',
            name='neighbourhood',
            field=models.TextField(blank=True, null=True),
        ),
    ]
