# Generated by Django 3.0.3 on 2020-04-14 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_airbnb_neighbourhood'),
    ]

    operations = [
        migrations.AddField(
            model_name='airbnb',
            name='room_type',
            field=models.TextField(blank=True, null=True),
        ),
    ]
