# Generated by Django 3.0.3 on 2020-04-15 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20200414_1659'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appstore',
            old_name='description',
            new_name='app_desc',
        ),
    ]
